># <center> <font color='red'> CMPE428 - DATA SCIENCE </font> </center>
>## <center> <font color='blue'> Assignment 2 - Data Representation Using Numpy </font>  </center>

Create a NumPy array named as 'myArray' of size 10x10 and fill it with random integers between 0 and 9

In [1]:
import numpy as np
np.random.seed(0) 
myArray=np.random.randint(0,9,(10,10))

print(myArray)

[[5 0 3 3 7 3 5 2 4 7]
 [6 8 8 1 6 7 7 8 1 5]
 [8 4 3 0 3 5 0 2 3 8]
 [1 3 3 3 7 0 1 0 4 7]
 [3 2 7 2 0 0 4 5 5 6]
 [8 4 1 4 8 1 1 7 3 6]
 [7 2 0 3 5 4 4 6 4 4]
 [3 4 4 8 4 3 7 5 5 0]
 [1 5 3 0 5 0 1 2 4 2]
 [0 3 2 0 7 5 0 2 7 2]]


Display the shape of the array

In [3]:
myArray.shape

(10, 10)

Display the sub-matrix having row indices 0,1,2 and column indices 3,4,5

In [7]:
array=myArray[0:3,3:6]
array

array([[3, 7, 3],
       [1, 6, 7],
       [0, 3, 5]])

Resphape the submatrix above to a row vector

In [8]:
array.reshape(1,9)

array([[3, 7, 3, 1, 6, 7, 0, 3, 5]])

Sort the elements in myArray row-wise and print the sorted matrix

In [12]:
np.sort(myArray)

array([[0, 2, 3, 3, 3, 4, 5, 5, 7, 7],
       [1, 1, 5, 6, 6, 7, 7, 8, 8, 8],
       [0, 0, 2, 3, 3, 3, 4, 5, 8, 8],
       [0, 0, 1, 1, 3, 3, 3, 4, 7, 7],
       [0, 0, 2, 2, 3, 4, 5, 5, 6, 7],
       [1, 1, 1, 3, 4, 4, 6, 7, 8, 8],
       [0, 2, 3, 4, 4, 4, 4, 5, 6, 7],
       [0, 3, 3, 4, 4, 4, 5, 5, 7, 8],
       [0, 0, 1, 1, 2, 2, 3, 4, 5, 5],
       [0, 0, 0, 2, 2, 2, 3, 5, 7, 7]])

Create a 1-D array of ones and stack it to myArray vertically

In [13]:
onesArray = np.ones((1, myArray.shape[1]))

# Stack it vertically with myArray
myArray = np.vstack((myArray, onesArray))
print(myArray)

[[5. 0. 3. 3. 7. 3. 5. 2. 4. 7.]
 [6. 8. 8. 1. 6. 7. 7. 8. 1. 5.]
 [8. 4. 3. 0. 3. 5. 0. 2. 3. 8.]
 [1. 3. 3. 3. 7. 0. 1. 0. 4. 7.]
 [3. 2. 7. 2. 0. 0. 4. 5. 5. 6.]
 [8. 4. 1. 4. 8. 1. 1. 7. 3. 6.]
 [7. 2. 0. 3. 5. 4. 4. 6. 4. 4.]
 [3. 4. 4. 8. 4. 3. 7. 5. 5. 0.]
 [1. 5. 3. 0. 5. 0. 1. 2. 4. 2.]
 [0. 3. 2. 0. 7. 5. 0. 2. 7. 2.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Add 10 to all elements in myArray

In [11]:
myArray=myArray+10
print(myArray)

[[15. 10. 13. 13. 17. 13. 15. 12. 14. 17.]
 [16. 18. 18. 11. 16. 17. 17. 18. 11. 15.]
 [18. 14. 13. 10. 13. 15. 10. 12. 13. 18.]
 [11. 13. 13. 13. 17. 10. 11. 10. 14. 17.]
 [13. 12. 17. 12. 10. 10. 14. 15. 15. 16.]
 [18. 14. 11. 14. 18. 11. 11. 17. 13. 16.]
 [17. 12. 10. 13. 15. 14. 14. 16. 14. 14.]
 [13. 14. 14. 18. 14. 13. 17. 15. 15. 10.]
 [11. 15. 13. 10. 15. 10. 11. 12. 14. 12.]
 [10. 13. 12. 10. 17. 15. 10. 12. 17. 12.]
 [11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]]


Add the vector [0,1,2,3,4,5,6,7,8,9] to each row

In [12]:
myArray=myArray+[0,1,2,3,4,5,6,7,8,9]
print(myArray)

[[15. 11. 15. 16. 21. 18. 21. 19. 22. 26.]
 [16. 19. 20. 14. 20. 22. 23. 25. 19. 24.]
 [18. 15. 15. 13. 17. 20. 16. 19. 21. 27.]
 [11. 14. 15. 16. 21. 15. 17. 17. 22. 26.]
 [13. 13. 19. 15. 14. 15. 20. 22. 23. 25.]
 [18. 15. 13. 17. 22. 16. 17. 24. 21. 25.]
 [17. 13. 12. 16. 19. 19. 20. 23. 22. 23.]
 [13. 15. 16. 21. 18. 18. 23. 22. 23. 19.]
 [11. 16. 15. 13. 19. 15. 17. 19. 22. 21.]
 [10. 14. 14. 13. 21. 20. 16. 19. 25. 21.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]]


Add 0 to all elements in the first row, 1 to second row, ... 10 to the last row

In [15]:
addValues = np.arange(myArray.shape[0]).reshape(-1, 1)

# Add these values to each row
myArray = myArray + addValues

print(myArray)

[[15. 11. 15. 16. 21. 18. 21. 19. 22. 26.]
 [17. 20. 21. 15. 21. 23. 24. 26. 20. 25.]
 [20. 17. 17. 15. 19. 22. 18. 21. 23. 29.]
 [14. 17. 18. 19. 24. 18. 20. 20. 25. 29.]
 [17. 17. 23. 19. 18. 19. 24. 26. 27. 29.]
 [23. 20. 18. 22. 27. 21. 22. 29. 26. 30.]
 [23. 19. 18. 22. 25. 25. 26. 29. 28. 29.]
 [20. 22. 23. 28. 25. 25. 30. 29. 30. 26.]
 [19. 24. 23. 21. 27. 23. 25. 27. 30. 29.]
 [19. 23. 23. 22. 30. 29. 25. 28. 34. 30.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]


Replace all elements of myArray above 20 with 0

In [16]:
myArray[myArray > 20] = 0
print(myArray)

[[15. 11. 15. 16.  0. 18.  0. 19.  0.  0.]
 [17. 20.  0. 15.  0.  0.  0.  0. 20.  0.]
 [20. 17. 17. 15. 19.  0. 18.  0.  0.  0.]
 [14. 17. 18. 19.  0. 18. 20. 20.  0.  0.]
 [17. 17.  0. 19. 18. 19.  0.  0.  0.  0.]
 [ 0. 20. 18.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 19. 18.  0.  0.  0.  0.  0.  0.  0.]
 [20.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [19.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [19.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


Replace all elements of myArray larger than 15 with their remainders when divided by 15

In [17]:
myArray[myArray > 15] = myArray[myArray > 15] % 15
print(myArray)

[[15. 11. 15.  1.  0.  3.  0.  4.  0.  0.]
 [ 2.  5.  0. 15.  0.  0.  0.  0.  5.  0.]
 [ 5.  2.  2. 15.  4.  0.  3.  0.  0.  0.]
 [14.  2.  3.  4.  0.  3.  5.  5.  0.  0.]
 [ 2.  2.  0.  4.  3.  4.  0.  0.  0.  0.]
 [ 0.  5.  3.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  4.  3.  0.  0.  0.  0.  0.  0.  0.]
 [ 5.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 4.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 4.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


Delete last 4 columns of myArray

In [21]:
myArray = myArray[:, :-4]
print(myArray)

[[15. 11. 15.  1.  0.  3.]
 [ 2.  5.  0. 15.  0.  0.]
 [ 5.  2.  2. 15.  4.  0.]
 [14.  2.  3.  4.  0.  3.]
 [ 2.  2.  0.  4.  3.  4.]
 [ 0.  5.  3.  0.  0.  0.]
 [ 0.  4.  3.  0.  0.  0.]
 [ 5.  0.  0.  0.  0.  0.]
 [ 4.  0.  0.  0.  0.  0.]
 [ 4.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


Delete last 3 rows of myArray

In [23]:
myArray=myArray[:-3,:]
print(myArray)

[[15. 11. 15.  1.  0.  3.]
 [ 2.  5.  0. 15.  0.  0.]
 [ 5.  2.  2. 15.  4.  0.]
 [14.  2.  3.  4.  0.  3.]
 [ 2.  2.  0.  4.  3.  4.]
 [ 0.  5.  3.  0.  0.  0.]
 [ 0.  4.  3.  0.  0.  0.]
 [ 5.  0.  0.  0.  0.  0.]]


Swap the second and third columns

In [30]:
myArray[:, [1, 2]] = myArray[:, [2, 1]]
print(myArray)

[[15. 15. 11.  1.  0.  3.]
 [ 2.  0.  5. 15.  0.  0.]
 [ 5.  2.  2. 15.  4.  0.]
 [14.  3.  2.  4.  0.  3.]
 [ 2.  0.  2.  4.  3.  4.]
 [ 0.  3.  5.  0.  0.  0.]
 [ 0.  3.  4.  0.  0.  0.]
 [ 5.  0.  0.  0.  0.  0.]]


Compute the sum of each row by multiplying myArray with a column vector of ones and print the results 

In [31]:
ones_vector = np.ones((myArray.shape[1], 1))

row_sums = np.dot(myArray, ones_vector)

print(row_sums)

[[45.]
 [22.]
 [28.]
 [26.]
 [15.]
 [ 8.]
 [ 7.]
 [ 5.]]


Split myArray into two matrices, A and B. A is made up of first 4 columns and B includes last 2 columns 

In [33]:
A=myArray[:,:4]
B=myArray[:,-2:]
print(A)
print(B)

[[15. 15. 11.  1.]
 [ 2.  0.  5. 15.]
 [ 5.  2.  2. 15.]
 [14.  3.  2.  4.]
 [ 2.  0.  2.  4.]
 [ 0.  3.  5.  0.]
 [ 0.  3.  4.  0.]
 [ 5.  0.  0.  0.]]
[[0. 3.]
 [0. 0.]
 [4. 0.]
 [0. 3.]
 [3. 4.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


Merge A and B back to myArray

In [36]:
myArray=np.hstack((A,B))
print(myArray)

[[15. 15. 11.  1.  0.  3.]
 [ 2.  0.  5. 15.  0.  0.]
 [ 5.  2.  2. 15.  4.  0.]
 [14.  3.  2.  4.  0.  3.]
 [ 2.  0.  2.  4.  3.  4.]
 [ 0.  3.  5.  0.  0.  0.]
 [ 0.  3.  4.  0.  0.  0.]
 [ 5.  0.  0.  0.  0.  0.]]


Normalize myArray so that each column is of zero mean and unit variance. Print the mean and variances of all columns to check for correctness 

In [37]:
mean = np.mean(myArray, axis=0)
std = np.std(myArray, axis=0)
myArray = (myArray - mean) / std
print(myArray)
print(np.mean(myArray, axis = 0))
print(np.std (myArray, axis = 0))

[[ 1.72913686  2.53776146  2.26913417 -0.64043572 -0.56965192  1.06748999]
 [-0.60632072 -0.70193402  0.35828434  1.67339657 -0.56965192 -0.76249285]
 [-0.06736897 -0.26997462 -0.59714057  1.67339657  2.03447115 -0.76249285]
 [ 1.54948627 -0.05399492 -0.59714057 -0.14461452 -0.56965192  1.06748999]
 [-0.60632072 -0.70193402 -0.59714057 -0.14461452  1.38344038  1.67748427]
 [-0.96562188 -0.05399492  0.35828434 -0.80570946 -0.56965192 -0.76249285]
 [-0.96562188 -0.05399492  0.03980937 -0.80570946 -0.56965192 -0.76249285]
 [-0.06736897 -0.70193402 -1.23409051 -0.80570946 -0.56965192 -0.76249285]]
[-2.25514052e-17  0.00000000e+00 -2.77555756e-17  5.55111512e-17
  8.32667268e-17 -2.77555756e-17]
[1. 1. 1. 1. 1. 1.]
